#!/usr/bin/env python3
"""
Builds index-readable.html from index.html, then proves the two match.

Why this exists
---------------
index.html is ~1.1 MB, but 91% of it is generated data: base64 artwork,
image paths and tags produced by the scripts in this repository. Reading
the code inside all that is unpleasant, so the repository also carries a
readable copy with those blocks replaced by a one-line note.

This script builds that copy AND verifies the claim behind it: outside the
data blocks, the two files are identical line for line. Run it to check
that claim yourself.

    python tools/readable-copy.py            # verify only
    python tools/readable-copy.py --write    # rebuild, then verify
"""

import io
import os
import re
import sys

AQUI = os.path.dirname(os.path.abspath(__file__))
RAIZ = os.path.dirname(AQUI)
PROD = os.path.join(RAIZ, "index.html")
COPIA = os.path.join(RAIZ, "index-readable.html")

# The generated blocks, in the order they appear, with what each one holds.
BLOCOS = [
    ("ASTD_TAGS",
     "Unit tags read from spreadsheet cell colours; generated by update_tags.py."),
    ("ASTD_VALOR_TEXTO",
     "Prices the Sheets API drops because they are text; generated by update_tags.py."),
    ("ASTD_IMAGES_CUSTOM",
     "Base64 unit artwork curated by the maintainer; generated by own_images.py."),
    ("ASTD_IMAGES",
     "Wiki artwork paths; generated by update_images.py."),
    ("ASTD_WIKI",
     "Wiki page titles per unit; generated by update_images.py."),
]

CABECALHO = (chr(13) + chr(10)).join([
    "<!-- ===================================================================",
    "     READABLE COPY — NOT RUNNABLE",
    "",
    "     Same file as index.html, with the generated data blocks replaced by",
    "     a short note. Those blocks are 91% of the original file and contain",
    "     no logic: base64 artwork, image paths and tags produced by the",
    "     local scripts.",
    "",
    "     Use this copy to read the code. Use index.html (untouched, byte for",
    "     byte what the live site serves) to compare against production.",
    "     ================================================================== -->",
    "",
])


def ler(caminho):
    return io.open(caminho, encoding="utf-8", newline="").read()


def construir(html):
    """Replace each data block and the favicon with a short note."""
    for nome, descricao in BLOCOS:
        marca = "window.%s = {" % nome
        ini = html.find(marca)
        if ini < 0:
            raise SystemExit("block not found in index.html: %s" % nome)
        fim = html.index("};", ini) + 2
        corpo = html[ini + len(marca):fim - 2]
        nota = ("%s /* %d entries, %d KB of generated data stripped for "
                "readability. %s */ };" % (marca, corpo.count('":'),
                                           max(1, len(corpo) // 1024), descricao))
        html = html[:ini] + nota + html[fim:]

    html = re.sub(r'(data:image/png;base64,)[^"]+',
                  r"\1[13 KB favicon stripped]", html)
    return CABECALHO + html


def sem_dados(html):
    """Strip the data blocks entirely, so both shapes normalise the same."""
    html = re.sub(r"<!-- =+\s*READABLE COPY.*?-->\s*", "", html, flags=re.S)
    for nome, _ in BLOCOS:
        marca = "window.%s = {" % nome
        while marca in html:
            ini = html.find(marca)
            html = html[:ini] + "DATA" + html[html.index("};", ini) + 2:]
    html = re.sub(r'(data:image/png;base64,)[^"]+', r"\1FAVICON", html)
    return [l.rstrip() for l in html.split("\n") if l.strip()]


def main():
    producao = ler(PROD)

    if "--write" in sys.argv:
        io.open(COPIA, "w", encoding="utf-8", newline="").write(construir(producao))
        print("wrote %s" % os.path.basename(COPIA))

    a, b = sem_dados(producao), sem_dados(ler(COPIA))
    print("index.html          %6d KB" % (len(producao) // 1024))
    print("index-readable.html %6d KB" % (os.path.getsize(COPIA) // 1024))

    if a == b:
        print("\nOK — %d comparable lines, identical in both files." % len(a))
        print("Only the generated data blocks differ.")
        return 0

    import difflib
    print("\nMISMATCH — the readable copy is out of date. Run with --write.")
    for linha in difflib.unified_diff(a, b, "index.html", "index-readable.html",
                                      lineterm="", n=0):
        print(linha[:120])
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
